language: java
deploy:
  provider: releases
  api_key: 
    secure: $GITHUB_API_KEY
  skip_cleanup: true
  file: target/releases/example-plugin-1.0-SNAPSHOT.zip
  on:
    repo: mark-ints/mvntrvs
    tags: true
script:
- mvn package -B
